language: node_js

node_js:
  - "10"

cache:
  directories:
    "node_modules"

script:
  - npm run build

deploy:
  provider: pages
  github_token: $GH_TOKEN
  skip_cleanup: true
  keep_history: true
  local_dir: public
  target-branch: gh-pages
  on:
    branch: master
